### ISSUE TITLE
Fix windows support,only import does not work.

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#169]
![2015-12-27 22-48-05](https://cloud.githubusercontent.com/assets/13142418/12011114/f43c9210-acfc-11e5-8761-1c36375736eb.png)
![2015-12-28 00-47-51](https://cloud.githubusercontent.com/assets/13142418/12011115/f4426fa0-acfc-11e5-907d-4a6d383967b5.png)
![2015-12-28 00-49-32](https://cloud.githubusercontent.com/assets/13142418/12011116/f44f1dae-acfc-11e5-8f1c-210218df67f7.png)

something maybe wrong here
```java
new Thread(() -> {
            Object o;
            if ((o = serializator.loadCache("class_packages")) != null) {
                classPackages = (HashMap<String, JavaClassMap>) o;
            } else {
                HashMap<String, JavaClassMap> classPackagesTemp = new HashMap<>();
                new PackagesLoader(Javavi.system.get("sources").replace('\\', '/'))
                    .collectPackages(classPackagesTemp);
                classPackages.putAll(classPackagesTemp);

                serializator.saveCache("class_packages", classPackages);
            }

            collectIsRunning = false;
        }).start();
```

**Comment by artur-shaik** [comment]
Can you try remove `replace()` method call?

**Comment by wsdjeg** [comment]
still can not complete import,if i use shellescape(),the socket will not be openned,@mattn

**Comment by adelarsq** [comment]
Same problem here. I was thinking that was something wrong with the classpath.

**Comment by wsdjeg** [comment]
classpath has no issue,because i can complete the manbers of instence or static method of Class

**Comment by wsdjeg** [comment]
also i think the issue maybe in these three class
PackagesLoader
ClasspathPackageSearcher
SourcePackageSearcher

**Comment by artur-shaik** [comment]
@wsdjeg made changes to this files. Try once more please.

**Comment by wsdjeg** [comment]
oh,just waitting for `Use `File.separator` everywhere`

**Comment by wsdjeg** [comment]
still same as second pic above,can not load packages,other completion is ok.also the plugin will open a extra windows which does not appear in linux terminal or gvim.
![2015-12-28 21-23-17](https://cloud.githubusercontent.com/assets/13142418/12019289/3f49acd2-ada9-11e5-9fa9-74299381b057.png)

**Comment by artur-shaik** [comment]
Some changes added. Try again, and show server startup logs, please.

**Comment by wsdjeg** [comment]
### complete logs
![2015-12-28 21-40-28](https://cloud.githubusercontent.com/assets/13142418/12019482/a45eefd6-adab-11e5-99cb-76735e0accbb.png)


### server restart logs
![2015-12-28 21-42-24](https://cloud.githubusercontent.com/assets/13142418/12019506/0636f244-adac-11e5-8885-8ae6ffe4877e.png)

**Comment by artur-shaik** [comment]
And nothing in `.javacomplete2/cache` ?

**Comment by wsdjeg** [comment]
yes,the directory is exists,but is empty

**Comment by artur-shaik** [comment]
Just to be sure, did you recompile server?

**Comment by wsdjeg** [comment]
of cource,i have done it

**Comment by adelarsq** [comment]
I did create a pull request to hide the server window on MS Windows (#171).

**Comment by artur-shaik** [comment]
Ok, guys, made some changes. Can you try again. Pull, recompile, clean cache.

**Comment by adelarsq** [comment]
Really nice. Imports are working now. :+1:

**Comment by wsdjeg** [comment]
@adelarsq are you sure everyting works well in win? i find import still can not work in xp os;maybe it works well in win7.

**Comment by adelarsq** [comment]
Yes. I didn't test so much, but even auto imports are working. I am using [vim-classpath](https://github.com/tpope/vim-classpath) to manage the classpath. I will disable tomorrow and see what happens.

**Comment by artur-shaik** [comment]
@wsdjeg can you enable server logging?
```
let g:JavaComplete_JavaviDebug = 1
let g:JavaComplete_JavaviLogfileDirectory = "C:\"
```

**Comment by wsdjeg** [comment]
here is the log
```
-base
-compiler
-D
Starting daemon mode

Exception in thread "Thread-2" java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: MALFORMED
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at kg.ash.javavi.searchers.PackagesLoader.collectPackages(PackagesLoader.java:22)
	at kg.ash.javavi.cache.Cache.lambda$collectPackages$0(Cache.java:42)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:566)
	at java.util.zip.ZipFile.access$900(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:524)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:499)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:480)
	at kg.ash.javavi.searchers.ClasspathPackageSearcher.lambda$loadEntries$19(ClasspathPackageSearcher.java:55)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at kg.ash.javavi.searchers.ClasspathPackageSearcher.loadEntries(ClasspathPackageSearcher.java:26)
	at kg.ash.javavi.searchers.PackagesLoader.lambda$collectPackages$3(PackagesLoader.java:22)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
-E
Search class: java
-p
-E
Search class: java.lang.Object
```

**Comment by adelarsq** [comment]
Even without [vim-classpath](https://github.com/tpope/vim-classpath) plugin did work.
The log shows the follow for java.* package:
```-base
-compiler
-D
Starting daemon mode

-E
Search class: java
java.nio.file.AccessDeniedException: com\dmp
java.nio.file.AccessDeniedException: config
java.nio.file.AccessDeniedException: ias
java.nio.file.AccessDeniedException: LogFiles\Fax\Incoming
java.nio.file.AccessDeniedException: LogFiles\Fax\Outgoing
java.nio.file.AccessDeniedException: LogFiles\Firewall
java.nio.file.AccessDeniedException: LogFiles\HTTPERR
java.nio.file.AccessDeniedException: LogFiles\WMI\RtBackup
java.nio.file.AccessDeniedException: Msdtc
java.nio.file.AccessDeniedException: NetworkList
java.nio.file.AccessDeniedException: spool\PRINTERS
java.nio.file.AccessDeniedException: Tasks
java.nio.file.AccessDeniedException: wbem\MOF
java.nio.file.AccessDeniedException: wdi
java.nio.file.AccessDeniedException: wfp
-p
```

**Comment by artur-shaik** [comment]
@wsdjeg ok, thanks. Let's try to catch it, try with last commit.

**Comment by wsdjeg** [comment]
@adelarsq @artur-shaik  this issue can be close safety
![2015-12-30 21-09-30](https://cloud.githubusercontent.com/assets/13142418/12051128/e0fe5b54-af39-11e5-9df9-f15ebc150fa5.png)
![2015-12-30 21-09-44](https://cloud.githubusercontent.com/assets/13142418/12051127/e0d6a474-af39-11e5-9c04-01d2fc670b92.png)
![2015-12-30 21-09-58](https://cloud.githubusercontent.com/assets/13142418/12051158/45b29ef2-af3a-11e5-838f-545519df4c18.png)

is there any issues?

**Comment by wsdjeg** [comment]
> Sometimes on MS Windows (Windows 7) the javavi process still are running after exit from Vim (GVim).

I do not encount this issue

**Comment by adelarsq** [comment]
Thanks @artur-shaik 
@wsdjeg It's random. I will try to figure out what is wrong before open a new issue.
