### ISSUE TITLE
Error on 'import static' completion

### ISSUE THREAD

**Issue by brailsmt** [artur-shaik/vim-javacomplete2#258]
## Actual behavior (Required!)
No dropdown, only a barely noticeable blip in the messages area.
Output from :messages:
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/MB013619/.vim/vim-plug/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 41, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/MB013619/.vim/vim-plug/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 67, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/MB013619/.vim/vim-plug/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 118, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/MB013619/.vim/vim-plug/vim-javacomplete2//rplugin/python3/deoplete/sources/javacomplete2.py", line 22, in gather_candidates
[deoplete]     0, context['complete_str'], 0)
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 213, in call
[deoplete]     return self.request('vim_call_function', name, args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 129, in request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(let):E121: Undefined variable: g:JC__CONTEXT_NEED_TYPE'
[deoplete] An error has occurred. Please execute :messages command.
```

## Expected behavior (Required!)
Static fields are provided in dropdown.

## The steps to reproduce actual behavior (Required!)
 1. Try to import a static member of a class.

## Environment (Required!)
 * OS: Mac OSX 10.10.5
 * Neovim version:
```
[mb013619]$ nvim --version
NVIM 0.1.4
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/build/config -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/src -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/deps-build/usr/include/luajit-2.0 -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/build/src/nvim/auto -I/tmp/neovim-20160504-23646-ax6are/neovim-0.1.4/build/include
Compiled by mb013619@MAC-MB013619

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.4/share/nvim"
```

## Q&A
* No, I have not tried minimal .vimrc configuration.  Too much effort, ATM, to determine what the minimal config would be.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

- I can't, the output contains proprietary information.

**Comment by artur-shaik** [comment]
Thank you for issue. Should be fixed now. Please, check.
