### ISSUE TITLE
Unable to autocomplete a GWT (Java to Javascript UI Framework) object 

### ISSUE THREAD

**Issue by gniding** [artur-shaik/vim-javacomplete2#324]
## Actual behavior (Required!)
Unable to autocomplete a GWT (Java to Javascipt UI Framework) object (com.google.gwt.user.client.ui.DialogBox)

0425 22:39:57.382 D [Thread-1] new  action: "GetClassInfoAction" [Javavi]
0425 22:39:57.384 D [Thread-1] executing search of "com.google.gwt.user.client.ui.DialogBox" [searchers.ClassSearcher]
0425 22:39:57.525 E [Thread-1] java.lang.ExceptionInInitializerError [Daemon]
java.lang.ExceptionInInitializerError: null
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_112]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_112]
        at kg.ash.javavi.readers.Reflection.exist(Reflection.java:55) ~[classes/:?]
        at kg.ash.javavi.searchers.ClassSearcher.find(ClassSearcher.java:29) ~[classes/:?]
        at kg.ash.javavi.actions.GetClassInfoAction.perform(GetClassInfoAction.java:16) ~[classes/:?]
        at kg.ash.javavi.Javavi.makeResponse(Javavi.java:113) ~[classes/:?]
        at kg.ash.javavi.Daemon.run(Daemon.java:68) [classes/:?]
Caused by: java.lang.UnsupportedOperationException: ERROR: GWT.create() is only usable in client code!  It cannot be called, for example, from server
        at com.google.gwt.core.shared.GWT.createImpl(GWT.java:77) ~[gwt-user-2.8.0.jar:?]
        at com.google.gwt.core.client.GWT.create(GWT.java:86) ~[gwt-user-2.8.0.jar:?]
        at com.google.gwt.user.client.ui.UIObject.<clinit>(UIObject.java:196) ~[gwt-user-2.8.0.jar:?]
        ... 7 more

## Expected behavior (Required!)
Should be able to autocomplete a GWT UI object (com.google.gwt.user.client.ui.DialogBox)
Eclipse can autocomplete GWT classes as they are functionally Java classes even though not intended to be run in a Java VM but in a browser as trans-compiled Javascript. Is there someway to handle GWT (e.g. bypassing the exception, GWT.create() call, or the no-arg constructor call) ?

## The steps to reproduce actual behavior (Required!)
 1. mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate \
   -DarchetypeCatalog=https://oss.sonatype.org/content/repositories/snapshots/ \
   -DarchetypeGroupId=net.ltgt.gwt.archetypes \
   -DarchetypeArtifactId=modular-webapp \
   -DarchetypeVersion=1.0-SNAPSHOT
 2. cd [package]-client
 3. vim src
 4. autocomplete on a DialogBox object

## Environment (Required!)
 * OS: Chromium OS 57
 * Vim version: 8.0
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by gniding** [comment]
There is a possible solution that I am testing:

Calling com.google.gwt.junit.GWTMockUtilities.disarm() before accessing the GWT UI classes
[GWT source](https://jar-download.com/explore-java-source-code-detail.php?file=./javaSource/com.google.gwt/gwt-user/2.8.0/com/google/gwt/junit/GWTMockUtilities.java&key=22c89fbf3a338aea2635a2b44d1d1bde)

**Comment by gniding** [comment]
This problem is FIXED by changing class kg.ash.javavi.readers.Reflection to:
1. call run com.google.gwt.junit.GWTMockUtilities.disarm() once 
2. normalize some GWT-specific class names within method 
```java
SourceClass lookup(String className) 
```
```java
    //begin of GWT support code
    private static void disarmGWT() {
        try {
         Class.forName("com.google.gwt.junit.GWTMockUtilities").getDeclaredMethod("disarm").invoke(null);
        } catch (Throwable e) {
        }
    }

    private String fixGwtClassForName(String className) {
        if (className.startsWith("java.lang.Iterable<com.google.gwt"))
            className = "java.lang.Iterable";
        else if (className.startsWith("java.lang.Comparable<"))
            className = "java.lang.Comparable";
        else if (className.startsWith("java$lang$") || className.startsWith("java.lang$"))
            className = "java.lang." + className.substring("java.lang.".length());
        else if (className.startsWith("com.google.gwt"))
            className = className.replace('$','.');
        return className;
    }

    static {
        // run com.google.gwt.junit.GWTMockUtilities.disarm() once to avoid GWT.create exception
        disarmGWT();
    }
    //end of GWT support code

    private SourceClass lookup(String className) {
        try {
            logger.debug("lookup class name: {}", className);

            // added for GWT specific class names support
            className = fixGwtClassForName(className);
            Class clazz = Class.forName(className);
            return getSourceClass(clazz);
        } catch (Exception ex) {
            logger.debug(String.format("error lookup %s", className), ex);
            return null;
        }
    }
```
