### ISSUE TITLE
Error while processing function provider#python#Call in Neovim 0.2

### ISSUE THREAD

**Issue by ronakg** [artur-shaik/vim-javacomplete2#327]
## Actual behavior (Required!)

When I open a .java file in neovim 0.2, I get following error. 

```
Error detected while processing function javacomplete#Start[1]..javacomplete#server#Start[46]..provider#python#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rogandhi/dotfiles/vim/plugged/vim-javacomplete2/autoload/javavibridge.py", line 70, in setupServer
    self.popen = SafePopen(args, env=environ, stdout = output, stderr = output)
  File "/home/rogandhi/dotfiles/vim/plugged/vim-javacomplete2/autoload/javavibridge.py", line 27, in SafePopen
    return subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
When I try to autocomplete a class variable, I get following backtrace:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/rogandhi/dotfiles/vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 121, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/rogandhi/.vim/plugged/vim-javacomplete2/rplugin/python3/deoplete/sources/javacomplete2.py", line 22, in gather_candidates
[deoplete] Traceback (most recent call last):
[deoplete]     0, context['complete_str'], 0)
[deoplete]   File "/home/rogandhi/dotfiles/vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 121, in gather_results
[deoplete]   File "/home/rogandhi/.local/lib/python3.5/site-packages/neovim/api/nvim.py", line 230, in call
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]   File "/home/rogandhi/.vim/plugged/vim-javacomplete2/rplugin/python3/deoplete/sources/javacomplete2.py", line 22, in gather_candidates
[deoplete]   File "/home/rogandhi/.local/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
[deoplete]     0, context['complete_str'], 0)
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/home/rogandhi/.local/lib/python3.5/site-packages/neovim/api/nvim.py", line 230, in call
[deoplete]   File "/home/rogandhi/.local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]     raise self.error_wrapper(err)
[deoplete]   File "/home/rogandhi/.local/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):Traceback (most recent call last):'
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete] Could not get completions from: javacomplete2.  Use :messages for error details.
[deoplete]   File "/home/rogandhi/.local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):Traceback (most recent call last):'
```

## Expected behavior (Required!)

None of the above mentioned errors should happen.

## The steps to reproduce actual behavior (Required!)
 1. Install deoplete and vim-javacomplete2
 2. Open a java file
 3. Try to do class variable autocompletion (e.g. class.method)

## Environment (Required!)
 * OS: Linux
 * Vim version: NA
 * Neovim version: NVIM v0.2.1-191-g060ce0e, Build type: Release

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

## The output of :redir and :message (Optional)

Provided above

**Comment by artur-shaik** [comment]
Hm, that's strange. Do you have `java` in `PATH`. Was compilation of server done after you open java file?

**Comment by ronakg** [comment]
It was indeed an issue with `java` and `PATH`. Not sure what changed, but I've been able to fix it.

Thanks.
