### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by brailsmt** [artur-shaik/vim-javacomplete2#344]
## Actual behavior (Required!)
On save of App.java from a newly created maven project.  
```Error detected while processing function <SNR>110_RemoveCurrentFromCache[7]..javacomplete#server#Communicate[2]..javacomplete#server#Start:
line   17:
E121: Undefined variable: port
E116: Invalid arguments for function add
Error detected while processing function <SNR>110_RemoveCurrentFromCache[8]..javacomplete#server#Communicate[2]..javacomplete#server#Start:
line   17:
E121: Undefined variable: port
E116: Invalid arguments for function add
Error detected while processing function <SNR>110_RemoveCurrentFromCache[13]..javacomplete#server#Communicate[2]..javacomplete#server#Start:
line   17:
E121: Undefined variable: port
E116: Invalid arguments for function add
```

## Expected behavior (Required!)
Success!

## The steps to reproduce actual behavior (Required!)
 1. mvn 
 2. vim $(find . -name App.java)
 3. :w

## Environment (Required!)
 * OS:  MacOSX 10.12.6
 * Vim version: 
 * Neovim version: 
```:version
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused
-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neo
vim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -
I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by 

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

## The output of :redir and :message (Optional)
```
"unit-test-example/src/main/java/com/cerner/devacademy/App.java" 13L, 184C
function javacomplete#Start[1]..javacomplete#server#Start[1]..<SNR>115_Poll[9]..provider#python#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 2 was closed by the client
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named neovim
Failed to load python host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
Error detected while processing function javacomplete#Start[1]..javacomplete#server#Start:
line   17:
E121: Undefined variable: port
E116: Invalid arguments for function add
"src/main/java/com/cerner/devacademy/App.java" 13L, 184C written
Error detected while processing function <SNR>110_RemoveCurrentFromCache[7]..javacomplete#server#Communicate[2]..javacomplete#server#Start:
line   17:
E121: Undefined variable: port
E116: Invalid arguments for function add
Error detected while processing function <SNR>110_RemoveCurrentFromCache[8]..javacomplete#server#Communicate[2]..javacomplete#server#Start:
line   17:
E121: Undefined variable: port
E116: Invalid arguments for function add
Error detected while processing function <SNR>110_RemoveCurrentFromCache[13]..javacomplete#server#Communicate[2]..javacomplete#server#Start:
line   17:
E121: Undefined variable: port
E116: Invalid arguments for function add
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
line    3:
E121: Undefined variable: s:serverVersionOutput
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
line    3:
E116: Invalid arguments for function join(s:serverVersionOutput)
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
line    3:
E15: Invalid expression: join(s:serverVersionOutput)
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
line    4:
E121: Undefined variable: serverVersion
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
line    4:
E116: Invalid arguments for function javacomplete#version#CheckServerCompatibility(serverVersion)
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
line    4:
E15: Invalid expression: !javacomplete#version#CheckServerCompatibility(serverVersion)
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
line   10:
E108: No such variable: "s:serverVersionOutput"
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
line    3:
E121: Undefined variable: s:serverVersionOutput
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
line    3:
E116: Invalid arguments for function join(s:serverVersionOutput)
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
line    3:
E15: Invalid expression: join(s:serverVersionOutput)
Error detected while processing function <SNR>57_JobNeoVimResponseHandler[3]..javacomplete#server#CheckServerAccordance:
```

Output of :CheckHealth:
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 0ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/bin/python"
  - INFO: Executable: /usr/bin/python
  - ERROR: Command error (21) /usr/bin/python -c import neovim; print(neovim.__file__): Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named neovim
  - INFO: Python2 version: 2.7.10
  - INFO: python-neovim version: unable to load neovim Python module
  - ERROR: Neovim Python client is not installed.
    Error: unable to load neovim Python module
    - SUGGESTIONS:
      - Run in shell: pip2 install neovim

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
  - INFO: Host: /Users/mb013619/.rvm/gems/ruby-2.1.2/bin/neovim-ruby-host
  - SUCCESS: Latest "neovim" gem is installed: 0.5.1
```

Output of `pip2 install neovim`:
```[20171011 15:20:18|mb013619]$ pip2 install neovim
Requirement already satisfied: neovim in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: greenlet in /usr/local/lib/python2.7/site-packages (from neovim)
Requirement already satisfied: msgpack-python>=0.4.0 in /usr/local/lib/python2.7/site-packages (from neovim)
Requirement already satisfied: trollius in /usr/local/lib/python2.7/site-packages (from neovim)
Requirement already satisfied: futures in /usr/local/lib/python2.7/site-packages (from trollius->neovim)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from trollius->neovim)
```

**Comment by brailsmt** [comment]
This was a PEBKAC of the first order.  I had the wrong python configured in neovim config.
